
SELECT DISTINCT A.* 
INTO #TEMP

		
FROM LY_ALUNO A
	INNER JOIN LY_GRADE G
		ON A.CURSO = G.CURSO
		AND A.CURRICULO = G.CURRICULO
		AND A.TURNO = G.TURNO
	INNER JOIN ly_CURSO C
		ON A.CURSO = C.CURSO
		AND C.TIPO IN ('SUP_SEI', 'SUP_SEPI')
	INNER JOIN LY_DISCIPLINA D
		ON G.DISCIPLINA = D.DISCIPLINA 	
	INNER JOIN LY_HISTMATRICULA H
		ON A.ALUNO = H.ALUNO
		AND H.SITUACAO_HIST NOT IN ('APROVADO')
	INNER JOIN LY_H_CURSOS_CONCL CC
		ON A.ALUNO = CC.ALUNO
		AND CC.MOTIVO = 'CONCLUSAO'
		AND CC.ANO_ENCERRAMENTO = '2022'

SELECT T.ALUNO, GE.* 
FROM #TEMP T
	INNER JOIN LY_GRADE_ELETIVAS GE 
	 ON T.CURSO = GE.CURSO
		AND T.CURRICULO = GE.CURRICULO
		AND T.TURNO = GE.TURNO
	WHERE NOT EXISTS (SELECT H.ALUNO FROM LY_HISTMATRICULA H WHERE T.ALUNO = H.ALUNO AND GE.DISCIPLINA = H.DISCIPLINA)



	SELECT * FROM LY_HISTMATRICULA WHERE ALUNO = '1229871' AND TURMA LIKE '%OPT%'






